spring:
  application:
    name: data

  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: wlood
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.type: true
      hibernate.use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE